### ISSUE TITLE
Wrong Item Requirements

### ISSUE THREAD

**Issue by jburleigh1** [osrsbox/osrsbox-db#98] opened 2019-04-15 14:26 UTC
Hey Tom!

Couple of issues that have appeared in my final testing of my BiS Tool with your new data. I'll update this thread as issues arise (or would you rather separate threads?)

All the God D'hide Shields have 0 requirements (should be 40 defence, 70 ranged)
Gilded Pickaxe has 0 requirements (should be 40 attack if it's the same as rune?)
Gilded D'hide Top has 0 requirements (if it's based on Green D'hide then it should be 40 ranged, 40 def)
Gilded D'hide Bottomhas 0 requirements (if it's based on Green D'hide then it should be 40 ranged)

Jamie

**Comment by osrsbox** [comment] 2019-04-15 19:18
Thanks for posting the issue, but this is a duplicate of #96. These items came in the last game update and haven't yet updated the skill requirements. But will hopefully get it done before this week's game update.

**Closed by osrsbox** 2019-04-15 19:18 UTC
Labels: duplicate

**Comment by jburleigh1** [comment] 2019-04-15 19:51
great :)
