### ISSUE TITLE
Just a small tweak

### ISSUE THREAD

**Issue by Nickenator8** [osrsbox/osrsbox-db#114] opened 2019-06-29 20:02 UTC
when choosing best ranged offence with 70+ range and 45 defence the calculator suggests black dhide, but blessed dhide is always a better choice over black dhide as it provides a small prayer bonus. The calc isn't wrong, it's all got the same range offense bonuses, but blessed is slightly better

Thanks for reading :D Sorry if this is in the wrong place, I don't use github very often

**Comment by osrsbox** [comment] 2019-06-29 21:31
Hey @Nickenator8 - not sure if this issue is relevant to my repository (my item database or the item database tools/scripts). From your description, it sounds like the issue is related to the osrsbestinslot.com web application? That web site uses my item database, but I am not the developer. I have tagged @jburleigh1 in this issue, as he is the web site developer and will probably be the person to contact.

If this is a problem with my item database project, please feel free to post a comment clarifying the problem. Will leave this issue open temporarily for the near future until resolved.

**Comment by osrsbox** [comment] 2019-07-05 02:28
Closing this issue as it seems not-related to this repository. If not, please feel free to re-open the issue.

**Closed by osrsbox** 2019-07-05 02:28 UTC
